### ISSUE TITLE
inline does not work

### ISSUE THREAD

**Issue by MauroMombelli** [alireza6677/arch-wiki-bot#5]
Inline is not working for @archwikibot but works for @archewikibot

**Comment by TheWeirdDev** [comment]
do you mean @archwikibot ?
My bot is offline because i don't have a server. I will contact the other bot's owner to see if he/she will accept to host the bot.

**Comment by MauroMombelli** [comment]
yes sorry, I updated the names. archEwikibot also bring me there, so i though where both run by you.I also have a "sleeping" VPN, and willing to run it (but that guy has already all up, so is worth a shot)

**Comment by TheWeirdDev** [comment]
Thanks! 
I contacted the owner and it seems like he accepted to run the bot. If he didn't, or there was any problem, i will get back to you.

**Comment by TheWeirdDev** [comment]
Seems working fine. Issue closed.
